language: go
go: 1.13.x
os: linux
services: docker

before_install:
  - docker build -t e.bedov https://github.com/EgorBedov/TechnoPark-RDBMS.git

before_script:
  - docker run --detach -p 5000:5000 --name e.bedov -t e.bedov
  - go get -u -v github.com/bozaro/tech-db-forum
  - go build github.com/bozaro/tech-db-forum

script:
  - ./tech-db-forum func -u http://localhost:5000/api || travis-terminate 1
  - ./tech-db-forum fill --timeout=900 || travis-terminate 1
  - ./tech-db-forum perf --duration=100 --step=10 || travis-terminate 1

after_script:
  - echo 'Success'